### ISSUE TITLE
Release 1.7 Tracking Bug

### ISSUE THREAD

**Issue by sbwsg** [spinnaker/spinnaker#2679]
This issue will remain open while we're working on the initial 1.7 release.

- [x] ECS support in Deck and Clouddriver
- [x] Kayenta: Resolve incompatibility between kayenta/orca https://github.com/spinnaker/kayenta/issues/291
- [x] Deck-Kayenta: The links from Canary Reports view to config and report sometimes don't work https://github.com/spinnaker/deck-kayenta/issues/292
- [x] Kayenta: Custom filter templates are being prematurely expanded https://github.com/spinnaker/kayenta/issues/293
- [x] Orca: https://github.com/spinnaker/spinnaker/issues/2690 https://github.com/spinnaker/orca/pull/2176#issuecomment-383996052
