### ISSUE TITLE
Proposal: Improve AWS EC2 / Spot Support

### ISSUE THREAD

**Issue by pdk27** [spinnaker/spinnaker#5989]
This issue proposes a bunch of new features in the AWS EC2 / Spot cloud provider area. 

**Status:** **All features are merged to master** ✅. Some are waiting to be released ⌛ in 1.28 . See the issue summary below for details. 
[Design document](https://docs.google.com/document/d/1wO4wxdZlnI1wXlUV4PF55Q0ZBbjWrt6YXdeh_a7Oqgw/edit#)
[SIG Design review/ meeting notes](https://docs.google.com/document/d/1wO4wxdZlnI1wXlUV4PF55Q0ZBbjWrt6YXdeh_a7Oqgw/edit#heading=h.f5iaps8k4cbf)  

### Features Tracker:
| Feature | Version | Released? |
|--------|-----|---|
|  Modify CPU credit spec (API) | 1.24 | ✅  |
|  Modify CPU credit spec (UI) | 1.24 | ✅  |
|  Support more instance types in burstable performance families (UI) | 1.24 | ✅  |
|  ASG Mixed Instances Policy (API) - Create ASG | 1.26 | ✅  |
|  ASG Mixed Instances Policy (UI) - View ASG | 1.26 | ✅  |
|  ASG Mixed Instances Policy (API) - Clone / Modify /Delete ASG | 1.27 | ✅  |
|  ASG capacity rebalancing support (API/UI) | 1.27 | ✅  |
|  Modify ASGs with LT to use MIP (API) | 1.27 | ✅  |
|  ASG Mixed Instances Policy (UI) - Create / Clone/ Delete ASG | 1.28 | ✅  |
|  Validation of instance types against architecture type of AMI (API) | 1.28 | ✅  |
| Display CPU credits for burstable performance instances types | 1.28 | ✅  |
| AWS EC2 / Spot best practice recommendations via helper texts (Deck feature) | 1.28 | ✅ |

Mixed Instances Policy feature includes:
1. Multiple instance types
2. Spot allocation strategies and diversification across a number of SpotInstancePools
3. Distribution of instances across purchase options - Spot and On-Demand
   
-----------

## Issue Summary
Spinnaker currently supports launching an AWS Server Group / Auto Scaling group (ASG) with a single instance type and a Spot max price. This issue tracks support for features mentioned in the above table.
     
**Prerequisite:**
Spinnaker must support AWS launch templates. 

## AWS EC2 Background
**AWS EC2 / Spot Instances:**
[AWS EC2 Spot Instances](https://aws.amazon.com/ec2/spot) represent unused EC2 capacity in AWS. They are available at up to a 90% discount compared to On-Demand prices. The caveat being that Spot instances can be interrupted and taken away by EC2 with a two minute notification. 
[AWS recommends some best practices](https://docs.aws.amazon.com/autoscaling/ec2/userguide/asg-purchase-options.html#asg-spot-best-practices) to maximize cost savings while minimizing the impact of interruptions. 
- diversify instances across capacity pools (instances in a pool have the same instance type, operating system, availability zone and network platform, and are priced the same)
- use Spot allocation strategies like capacity optimized to provision spot instances from the deepest capacity pools, lowering the possibility of interruptions

**Burstable Performance Instances:** 
The key difference between t2 and t3 instance types is the AWS default credit specification when they launch. The AWS EC2 defaults are:
* T3 instances launch as unlimited by default.
* T2 instances launch as standard by default.

## Feature Area
Deck - ServerGroups, Clouddriver, Gate

## Proposal
**Deck:** 
The new features will be accessible by enabling a custom setting. All new features proposed here require support for launch templates to be enabled. 

**High-level changes:**

1. Changes to _Instance Type_ section of the _Create Server Group_ wizard (mocks below)
2. Changes to ServerGroup details to accommodate changes from #1
3. Validations for new fields
5. _Spot Instances Price_ field under _Advanced Settings_ will be moved under _Instance Type_(as it makes more sense for the user to think about it while in the _Instance Type_ section)

**Mocks:**
Note: By default, all selected instance types will be weighted equally (i.e. weight of 1). The user will have the ability to modify the weights. 
 
<img src="https://user-images.githubusercontent.com/3614196/90691933-cf784380-e239-11ea-8fa3-82450cf4cd6a.png" width="300" height="400" />  <img src="https://user-images.githubusercontent.com/3614196/90692120-29790900-e23a-11ea-8fbd-19544445ce09.png" width="300" height="400" />
<img src="https://user-images.githubusercontent.com/3614196/90692180-4e6d7c00-e23a-11ea-9a3f-0dda5608737b.png" width="300" height="400" />
<img src="https://user-images.githubusercontent.com/3614196/90692187-50373f80-e23a-11ea-8828-3c16961cd6a3.png" width="300" height="400" /><img src="https://user-images.githubusercontent.com/3614196/90692191-53cac680-e23a-11ea-8f04-161337638f97.png" width="300" height="400" />

**Clouddriver:**
Changes to support the UI features. Primarily, 
- Add support for the ASG MixedInstancesPolicy feature, conditionally launching an AWS ASG with mixed instances policy when overrides / instances distribution configurations are used.
- Add support for CPU credits while creating launch template

**Gate**
API changes and samples: 
_Note: The samples only show relevant fields_
* Create task request:
`curl -d '{<request payload below>}'  -H 'Content-Type: application/json'  https://spinnaker-host:8084/tasks
`
   * Valid request payload:
      ![image](https://user-images.githubusercontent.com/3614196/92007505-aa8cd180-ed0b-11ea-8c63-4c8db7711a62.png)

  * Invalid request payload:
     ![image](https://user-images.githubusercontent.com/3614196/92007575-bed0ce80-ed0b-11ea-85a5-6795baef3aa0.png)

* Get task response:
`curl -X GET https://spinnaker-host:8084/tasks/<my-invalid-task-id>
`
  * Get after invalid create task:
    ![image](https://user-images.githubusercontent.com/3614196/92006570-867cc080-ed0a-11ea-99f7-97c8b8b6ced5.png)

## Additional Details
Addition details can be found in the design document linked at the top.

## Feedback Requested
If you use the AWS provider and Spot instances, we'd like to hear feedback on the proposed changes. 
For AWS EC2 / Spot feedback not related to this proposal, leave feedback [here](https://github.com/aws/ec2-spot-instances-integrations-roadmap/issues/11).

**Comment by avram** [comment]
This looks really good and covers our major known use cases for using Spot with Spinnaker. 

It looks like the instance weights may have good defaults-- is that going to be something we can count on, that it will default to weighting aligned with vCPU counts?

**Comment by pdk27** [comment]
> It looks like the instance weights may have good defaults-- is that going to be something we can count on, that it will default to weighting aligned with vCPU counts?

@avram the current proposal doesn't include weight recommendations as instance weighting can be customized across various parameters. We will look into simple weight recommendations based on vCPU counts for the non-custom type selection categories in `Instance Type` section of Deck. 

Instance weighting recommendations for `custom type` will probably be trickier and more involved. We have a follow-up item for evaluating the idea of recommendations.

**Comment by pdk27** [comment]
> Looks good! I think it would be helpful to add a sample of the new API request, especially for API users who are not relying on the UI as much. Maybe just highlighting what the added fields are named and their types and/or any defaults.

Sure, Casey. Looking into it. Will update the proposal soon.

**Comment by noahi** [comment]
Awesome! 

I have lots of little thoughts: 
1. Is there a reason the Enable CPU toggle is a check box, and the Show all types toggle is a slider? 
2. given that the type checkbox is on the left column, maybe swap the two toggles above, so the show selected/all toggle is above the checkbox for each type? 
3. Just how tall is the "Select an instance type..." dropdown? Is it sorted? Do users know what those types mean? (Personal pet peeve: I tried to get AWS to build a better instance picker for years when I worked there. It never happened.)
4. does it make sense to bubble selected instance types to the top? that would make prioritization easier, but ruins the sort order. 
4a. might make the "show only selected' option redundant though.
5. with custom types will users know the CPU, mem, storage, etc? 

This is exicting!

**Comment by christopherthielen** [comment]
From the screenshots, it looks like this UI fully replaces the "simple" instance type picker.  Is there a UI toggle that switches back to the existing behavior?

w.r.t the weight ordering in the mockup: just wanted to point out that we currently sort most things in Deck using a drag/drop sorter widget (see the pipelines sort functionality)

**Comment by pdk27** [comment]
@noahi 
> 1. Is there a reason the Enable CPU toggle is a check box, and the Show all types toggle is a slider?

These mocks were put together quickly to indicate the high-level direction of the design. 
We can make these consistent 👍 
> 2. given that the type checkbox is on the left column, maybe swap the two toggles above, so the show selected/all toggle is above the checkbox for each type?

It makes sense to move the show selected/all toggle to the left. 
> 3. Just how tall is the "Select an instance type..." dropdown? Is it sorted? Do users know what those types mean? (Personal pet peeve: I tried to get AWS to build a better instance picker for years when I worked there. It never happened.)
> 5. with custom types will users know the CPU, mem, storage, etc?

The "Select an instance type..." dropdown is very long today and the length will not be impacted by these features - it might only get longer and more descriptive with some improvements suggested in the design document :) 
1. Add information like vcpu, memory, usage classes supported, virtualization, storage type to instance type drop-down list when custom type is chosen
2. Mark or remove already selected instance types in drop-down for the multiple instance types case.

1#  requires integrating with a recently launched[ EC2 Describe Instance Types API](https://docs.aws.amazon.com/cli/latest/reference/ec2/describe-instance-types.html). So, this will a follow-up after the main deliverables in the design.

> 4. does it make sense to bubble selected instance types to the top? that would make prioritization easier, but ruins the sort order.
>    4a. might make the "show only selected' option redundant though.

Not sure if this would make sense as the order of the selected instance types will be used for order when [On Demand allocation strategy prioritized](https://docs.aws.amazon.com/autoscaling/ec2/APIReference/API_InstancesDistribution.html) is chosen. 

We are considering the instance types table under non-custom type to be sortable (this feature is missing in the mocks). But, this could lead to undesired order of instance types in the AWS request. Will bring this up in review tomorrow and would like to hear more thoughts on this.

**Comment by pdk27** [comment]
@christopherthielen 
> From the screenshots, it looks like this UI fully replaces the "simple" instance type picker. Is there a UI toggle that switches back to the existing behavior?

By "simple" instance type picker, are you referring to the current state of `Instance Type` section where none of the features listed here are supported? 
The proposed features require support for launch templates to be enabled and will be accessible by enabling a custom setting (we are still evaluating what this looks like for the customer)
So, customers who want these features will make this change in their setting and only see the `Instance Type` section with the new features. 

A UI toggle to switch between proposed features or no proposed features wouldn't suffice because of the dependency on launch template setting, is my understanding -> this toggle will be in the build settings. 

> w.r.t the weight ordering in the mockup: just wanted to point out that we currently sort most things in Deck using a drag/drop sorter widget (see the pipelines sort functionality)

Great! We will try to keep it consistent.

**Comment by akshayabd** [comment]
LGTM - looking forward to seeing this available!

If you encounter any issues/blockers please bring them up in follow-up SIG meetings.

**Comment by noahi** [comment]
@pdk27 Fantastic! Just a one extended remark below. Everything not addressed here is awesome. Sorry I didn't get back to see this feedback sooner. 


> > 4. does it make sense to bubble selected instance types to the top? that would make prioritization easier, but ruins the sort order.
> >    4a. might make the "show only selected' option redundant though.
> 
> Not sure if this would make sense as the order of the selected instance types will be used for order when [On Demand allocation strategy prioritized](https://docs.aws.amazon.com/autoscaling/ec2/APIReference/API_InstancesDistribution.html) is chosen.

I meant bubble to the top for display purposes, but not prioritization purposes. This also implies / assumes that anything checked is probably being prioritized, and anything being prioritized is automatically checked. I'm not sure those things are true right now, but they are worth considering. 

Regarding (display) sort order, if checked items were bubbled to the top of the list, I'd consider the column sort to be a secondary sort, after checked/not checked. Prioritization rank would not affect (display) sort order.

**Comment by pdk27** [comment]
Thanks @noahi @christopherthielen and SIG UI for all the comments. 
Here are meeting notes for the SIG UI discussion - https://docs.google.com/document/d/1wO4wxdZlnI1wXlUV4PF55Q0ZBbjWrt6YXdeh_a7Oqgw/edit#heading=h.f5iaps8k4cbf

**Comment by spinnakerbot** [comment]
This issue hasn't been updated in 45 days, so we are tagging it as 'stale'. If you want to remove this label, comment:

> @spinnakerbot remove-label stale

**Comment by pdk27** [comment]
@spinnakerbot remove-label stale

**Comment by spinnakerbot** [comment]
This issue hasn't been updated in 45 days, so we are tagging it as 'stale'. If you want to remove this label, comment:

> @spinnakerbot remove-label stale

**Comment by pdk27** [comment]
@spinnakerbot remove-label stale

**Comment by pdk27** [comment]
Plan for PRs related to multiple instance types feature additions in Deck:
1.  [Updates to types and hard-coded values (instance type details for non-custom instance type selector) ](https://github.com/spinnaker/deck/pull/9661)
2. [New child components for AWS EC2 Instance Type wizard](https://github.com/spinnaker/deck/pull/9653)
3. New and updates to existing parent components for AWS EC2 instance type wizard and AWS services related changes 
4.  Updates to pipeline + server group wizards

The PRs will be cut to master with each part with appropriate labels and will be merged in the order mentioned (only after the checks pass).

**Comment by pdk27** [comment]
## Manual tests:
- Screenshots and features listed below
- CloneServerGroup with combinations of launch configuration, launch template, and mixed server groups 
- CreateServerGroup with launch configuration, launch template, and mixed server groups 

## Todo: 
- instance type validation w.r.t. image/ AMI's architecture type to ensure a valid combination of types to follow (requires backend change) 
- [part 3 and part 4 PRs to follow](https://github.com/spinnaker/spinnaker/issues/5989#issuecomment-920301104)
- this PR will be merged only after [part 1 ](https://github.com/spinnaker/deck/pull/9661)is merged and checks pass


## Screenshots and gifs
<details>
<summary>Simple Mode (should match current version of InstanceType wizard with single instance type)</summary>

https://user-images.githubusercontent.com/3614196/133356578-23a0cb78-f942-49c8-a672-68e79c18fd00.mov

</details>

-----

<details open>
<summary>Advanced Mode</summary>

#### Features: 
    - [x] Supports multiple instance types + instance weighting
    - [x] Profile change retains only the instance types in new profile (discards the others) 
    - [x] Add weight first and then add new instance type or Add new instance type and then update weight 
    - [x] CpuCredits Toggle is displayed when applicable for ALL instance types (reset otherwise)
    - [x] Sorting with drag handle means priority is changed for selected instance types 

https://user-images.githubusercontent.com/3614196/133357723-e5c5ac52-5612-4902-be1a-360e8cd2302b.mov


</details>

-----

<details>
<summary>Mode Change</summary>

#### LaunchTemplates support disabled
![image](https://user-images.githubusercontent.com/3614196/132926893-fda67131-2f6c-4e40-b203-be3cf671df65.png)


#### LaunchTemplates support enabled
![image](https://user-images.githubusercontent.com/3614196/132927013-ee4efbeb-d43f-49b7-8d23-293cffb85170.png)


#### Simple mode -> Advanced mode &  Advanced mode -> Simple mode

https://user-images.githubusercontent.com/3614196/133356526-bae8bb46-0615-470f-ad9d-ef20fa70ca72.mov

</details>

---

<details>
<summary>Validations</summary>

https://user-images.githubusercontent.com/3614196/133353852-781ba92c-cbec-4fd0-bb6f-95ba8338a25a.mov

</details> 

-----

<details>
<summary>Unavailable instance types (w.r.t. image virtualization type) </summary>
<img src="https://user-images.githubusercontent.com/3614196/132927088-9fd93687-2103-4b22-8df8-a1b5b6ba20ae.png" width="400" height="600" />

<img src="https://user-images.githubusercontent.com/3614196/132927213-a9d99c52-0798-40c2-b35d-2aaee1e524fd.png" width="400" height="800" />

</details>

-----

<details>
<summary>Pipelines</summary>

https://user-images.githubusercontent.com/3614196/133357828-370f51b3-2993-424c-89e1-d0e2405bfa59.mov


</details>

**Comment by pdk27** [comment]
Closing the issue as all related PRs have been released.
