### ISSUE TITLE
Spinnaker Releases - Rewrite Release Runbook Docs

### ISSUE THREAD

**Issue by kskewes-sf** [spinnaker/spinnaker#6627]
**Current status**:

There is a [runbook](https://spinnaker.io/docs/releases/release-manager-runbook/) on the website for cutting releases.
It references various Jenkins jobs which are no longer available as Jenkins is not running and won't be restored.

**Objectives**:

A release manager can follow the runbook to cut a release (minor or patch). 

**Tasks**:
- [x] replace jenkins steps with appropriate [`hal admin`](https://github.com/spinnaker/halyard/tree/a036362b27581abeb83de99d682f0e200d12f1e1/halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/admin), [buildtool](https://github.com/spinnaker/buildtool/), [spinrel](https://github.com/spinnaker/spinrel) (specifically [SpinnakerVersionPublisher.kt](https://github.com/spinnaker/spinrel/blob/master/jenkins-cli/src/main/kotlin/io/spinnaker/spinrel/cli/jenkins/SpinnakerVersionPublisher.kt)) steps or equivalent shell
- [x] placeholder for any integration tests (see: non goals)
- [x] consider adding artifact URL's, breakdown of naming convention for use in verification steps
  - bom: https://console.cloud.google.com/storage/browser/_details/halconfig/
  - containers: https://console.cloud.google.com/artifacts/docker/spinnaker-community/us/docker
  - debs: https://console.cloud.google.com/artifacts/apt/spinnaker-community/us/apt
  - jars: https://repo.maven.apache.org/maven2/io/spinnaker/
  - spin binary: https://console.cloud.google.com/storage/browser/spinnaker-artifacts/spin
- ~consider adding changelog gist and other links for use in verification steps~ Not required, changelog gists no longer created.
- [x] changes from old way
- [x] explain pushing additional tag without `unvalidated` even though Integration Tests not run - BOM Halyard /debs/etc

**Non goals**:
- Integration Test running on Google Cloud Build
- Investigate moving Changelog gists from gist to spinnaker.io repo files
