### ISSUE TITLE
Spinnaker Releases - Integration Test Job Investigation

### ISSUE THREAD

**Issue by kskewes-sf** [spinnaker/spinnaker#6628]
**Current status**:

Integration tests were previously run nightly in Google Cloud Build orchestrated by Jenkins(gone).
One of the outputs from a successful test run was updating container image tags from `unvalidated` to `validated`.
See references in: https://spinnaker.io/docs/releases/release-manager-runbook/

**Objectives**:

Define an implementation method for running Integration Tests. 
This plan would ideally include source code management of the test orchestration files (akin to `Jenkinsfile`'s) so that the community can review and manage the jobs like the rest of the Spinnaker project.

**Tasks**:
- [ ] review existing test suite: https://github.com/spinnaker/buildtool/tree/master/testing/citest
- [ ] investigate how the tests could be triggered/orchestrated instead of Jenkins. 
  - Scheduled or triggered GitHub Action's?
  - Scheduled or trigger GCP Cloud Build?
  - Other?
- [ ] Prepare proposal on how tests could be run and managed.

**Non goals**:
- getting integration test suite running
- adding additional new integration tests
- running any tests that require cloud accounts other than what is already accessible (GCP?)
- 100% coverage of existing test suite. As a first pass we should aim to get MVP down with whatever the implementation is.

**Comment by spinnakerbot** [comment]
This issue hasn't been updated in 45 days, so we are tagging it as 'stale'. If you want to remove this label, comment:

> @spinnakerbot remove-label stale
